server:
  port: ${PORT:5001}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:123456}